### ISSUE TITLE
Rename 'config' parameter of cli.run()

### ISSUE THREAD

**Issue by pylipp** [pylipp/financeager#17]
It's not holding a config(uration) but rather the path where the custom config file resides.
Replace by e.g. `config_path`, and update the corresponding long command line option to `--config-path`.

**Comment by cardinalion** [comment]
Hey, I happened to see here. I'm kind of new, do you mean this part?
`subparser.add_argument(
            "-C",
            "--config",
            help="path to config file. Default: {}".format(
                financeager.CONFIG_FILEPATH))`
And do you plan to update the path in _load_custom_config()? 
Sorry, I'm not helping.

**Comment by pylipp** [comment]
Hej, thanks for asking, you're very close :)
Yes, "--config" shall become "--config-path", and [here](https://github.com/pylipp/financeager/blob/master/financeager/cli.py#L38) `config=None` should become `config_path=None`.
There's probably some small things to adjust in the tests as well.
You can try, and reach out to me again :)

**Comment by pylipp** [comment]
I think the naming `--config-filepath` is even better, to be conform with the constant `financeager.CONFIG_FILEPATH`.

**Comment by cardinalion** [comment]
AH, now I get what you mean
