### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by DustinTheGreat** [pylipp/financeager#20]
This needs a requirements.txt for making it easier to collaborate on.

**Comment by pylipp** [comment]
Hej, thanks for your input! Can you explain why this is considered good practice, or how it would help collaboration?
I had a requirements.txt back in the days but moved the content to the `install_requires` option in `setup.py`.

**Comment by DustinTheGreat** [comment]
it probably isn't, I always thought that it was the norm to have both.

**Comment by pylipp** [comment]
I think that conflicts a little with the 'principle of single source'; this way either source is prone to become outdated by accident.
The advantage of having it in `setup.py` is that dependencies are automatically installed when you do e.g. a `pip install -e .`. If you have requirements.txt only, you have to add the `-r requirements.txt` option.
