### ISSUE TITLE
Add a "Remaining" field for the list command

### ISSUE THREAD

**Issue by IJustDev** [pylipp/financeager#29]
The print command should display a "remaining" field below the total income and expenses.

```
              Earnings                |               Expenses               
Name               Value    Date  ID  | Name               Value    Date  ID 
=============================================================================
Total              000.00             | Total              000.00          
Remaining          0.00
```

**Comment by pylipp** [comment]
You mean the difference `earnings - expenses`? That's a great idea! Want to start implementing it?

**Comment by IJustDev** [comment]
Sure I'll try my best. I'm new to this kind of python development. Can you please give some instructions on how to keep on developing this project? This could also be a future part of the readme.
