### ISSUE TITLE
Move '_format_response' into cli module

### ISSUE THREAD

**Issue by pylipp** [pylipp/financeager#31]
- functionality specific to cli, not to Client API
- requires wrapping logger.info for Out.info

**Comment by cardinalion** [comment]
what is logger.info?

**Comment by pylipp** [comment]
`logger.info` is a logging function provided by a Logger object: https://docs.python.org/3/library/logging.html#logging.Logger.info

**Comment by uliana291** [comment]
I'll take that

**Comment by uliana291** [comment]
I'm not sure I understand the task:
- `_format_response` is used in Client.run in financeager/communication.py
- result of Client.run is used in out.info in safely_run
- therefore if Client.Out.info will use _format_response on message which is already formatted inside Client.run, which is going to change behaviour
- so, either signature of Client.run has to be changed (remove usage of _format_response), or Client.Out shoudn't use _format_response

**Comment by pylipp** [comment]
Hej, thanks for having a look :)
My thoughts were that `_format_response` is moved to the `cli` module, meaning it is removed in `Client.run()`. When a Client is instantiated in the context of `cli`, i.e. in `cli.run()`, it obtains an Out-object that has an `info` function (as sketched above) and the `logger.error` function.

**Comment by pylipp** [comment]
@uliana291 do you still want to work on this one? I'd like to include it in the next release tomorrow. No problem either to implement it myself ;)

**Comment by uliana291** [comment]
No thank you. Good luck with release ;)
