### ISSUE TITLE
Tests are fragile and cross-platform incompatible.

### ISSUE THREAD

**Issue by babhishek21** [pylipp/financeager#36]
As mentioned in https://github.com/pylipp/financeager/issues/11#issuecomment-542212160 , the tests are fragile and/or cross-platform incompatible.

On Windows 10 x64 I had 10 tests failing.
On MacOS Mojave I had 2 tests failing:

1. 
```
======================================================================
FAIL: test_invalid_host (test.test_httprequests.HttpRequestProxyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/abhibha/misc/financeager/test/test_httprequests.py", line 51, in test_invalid_host
    self.assertIn("Name or service not known", error_message)
AssertionError: 'Name or service not known' not found in "Error sending request: HTTPConnectionPool(host='weird.foodomain.nope', port=80): Max retries exceeded with url: /periods/2000/standard/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107d51e90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))"
```

Testing on error explanations is generally a bad idea. As seen here, for MacOS, the underlying error explanation is significantly different from most Linux ones: `nodename nor servname provided, or not known`.

Instead, test on the exact error type as much as possible. In this case that'd be `NewConnectionError` thrown by urllib3, which should be the same across platforms.

2.
```
======================================================================
FAIL: test_verbose (test.test_cli.CliLocalServerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/mock.py", line 1209, in patched
    return func(*args, **keywargs)
  File "/Users/abhibha/misc/financeager/test/test_cli.py", line 150, in test_verbose
    "Loading custom config from {}".format(TEST_CONFIG_FILEPATH)))
AssertionError: False is not true
```
Classic case of new lines / whitespace breaking tests. The actual string printed to **stderr** (at-least on my Mac) is: 
```
DEBUG 2019-10-15 18:58:48,266 financeager.config:48 Loading custom config from /tmp/financeager-test-config

```
Take note of the newline. `string.endswith` obviously fails. Instead, let's use `in`.

**Comment by pylipp** [comment]
Hej, thanks for the detailed investigation; I was not aware of the platform differences.
Your solutions sound very sensible.
Do you mind submitting fixes?
