### ISSUE TITLE
Remove warnings about unclosed file after running tests

### ISSUE THREAD

**Issue by pylipp** [pylipp/financeager#39]
When running `python setup.py test` several warnings are shown at the end:

    sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/financeager-qyuh0cmu/1909.json' mode='r+' encoding='UTF-8'>

This could be due to `tearDownClass()` in `test_cli` stopping the webservice without invoking closing the period database files (e.g. via `Server.run('stop')`).

**Comment by Joel-hanson** [comment]
Shall I take this up @pylipp

**Comment by pylipp** [comment]
Sure, go ahead! Thanks :)

**Comment by Joel-hanson** [comment]
Hi @pylipp ,

I have made a pull request #42  that can solve this issue.

Thanks in advance.
